name: Executar Palpites Diariamente

on:
  schedule:
    - cron: '0 8 * * *'  # 09:00 em Angola (UTC+1)
  workflow_dispatch:

jobs:
  rodar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Criar arquivo .env
      run: |
        echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
        echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env

    - name: Executar script
      run: python palpites.py
