name: Enviar Palpites Diários

on:
  schedule:
    - cron: '0 8 * * *'  # Roda às 08:00 UTC (09:00 em Angola)
  workflow_dispatch:     # Permite executar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Criar .env
      run: |
        echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
        echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env

    - name: Executar script de palpites
      run: python palpites.py
